### ISSUE TITLE
Consensus container enabled: No

### ISSUE THREAD

**Issue by marzapps** [pi-node/instructions#106]
I am stuck, I have had the node running for about two days and nothing has changed on the Diagnostics Info.  Do I have to wait longer? Also it shows my availability is only 18% but my computer has been up the entire two days.  I did a port scan and all the ports are open and I see the stellar-dummy docker running.

Container
Consensus container enabled: No
Node switch on: Yes
PortsChecker container: running
Consensus container: absent

Consensus
State: N/A
Protocol version: N/A
Latest block: N/A
Outgoing connections: N/A
Incoming connections: N/A
Supporting other nodes: No

Other
Pi Node version number: 0.4.3
Operating system: MAC 17.7.0 (High Sierra)
Using Docker Toolbox: No
Node installation date: 2021-04-13
Availability (up to 90 days): 18.06% from 2021-04-13 to 2021-04-15

Port Scan:
Host is up (0.094s latency).
PORT      STATE  SERVICE
31400/tcp open  pace-licensed
31401/tcp open  unknown
31402/tcp open  unknown
31403/tcp open  unknown
31404/tcp open  unknown
31405/tcp open  unknown
31406/tcp open  unknown
31407/tcp open  unknown
31408/tcp open  unknown
31409/tcp open  unknown

**Comment by nathusius** [comment]
I am on Windows and in same position as you, but had a wait a lot longer than two days before I saw ANY availability in the diag window! Now I think you just have to wait longer and see if you get selected as a test Node, then the consensus container will be downloaded to Docker and you should see Consensus running instead of PortChecker. I could not get Pi Node to ping test the ports at all, but they were all reported as open from the port scan at https://www.ipfingerprints.com/portscan.php so I just left it running and now hope to get selected too! Good luck ;-)

**Comment by marzapps** [comment]
> I am on Windows and in same position as you, but had a wait a lot longer than two days before I saw ANY availability in the diag window! 

Weird, now almost 24 hours later my Availability still reads exactly the same, yet its been up and running for three full days:
_Availability (up to 90 days): 18.06% from 2021-04-13 to 2021-04-15_

**Comment by nathusius** [comment]
Same with mine, I left the PC on overnight since availability first registered, but the figure is identical, so it doesn't seem to update very often - guess we just leave it now and see what happens over the next while

**Comment by nathusius** [comment]
My availability has now updated, three days since the first figure appeared (15th to 18th April) - the new figure has dropped slightly, even though te PC has been left on permanently since the 15th, so it's all a bit odd!

**Comment by marzapps** [comment]
So my availability did update from 18 to 40% again its been pretty much up the whole time...
Also I started getting pop-ups saying my OS wasn't supported, took me a while to figure out they were coming from the PI app (they had no label on the window).  So I updated to Big Sur everything seems to be running fine but still no Consensus Container.

Diagnostics Info
Container
Consensus container enabled: No
Node switch on: Yes
PortsChecker container: running
Consensus container: absent

Consensus
State: N/A
Protocol version: N/A
Latest block: N/A
Outgoing connections: N/A
Incoming connections: N/A
Supporting other nodes: No

Other
Pi Node version number: 0.4.3
Operating system: MAC 20.3.0 (undefined)
Using Docker Toolbox: No
Node installation date: 2021-04-13
Availability (up to 90 days): 40.54% from 2021-04-13 to 2021-04-17

**Comment by nathusius** [comment]
No, I don't have Consensus container yet either, so we are in much the same position - can't do much but hodl and hope!! ;-)

**Comment by nathusius** [comment]
OK, as of this morning, I do now have the Consensus container installed and all sync'd up to other nodes:

Diagnostics Info
Container
Consensus container enabled: Yes
Node switch on: Yes
PortsChecker container: exited
Consensus container: running

Consensus
State: Synced!
Protocol version: Latest
Latest block: a few seconds ago
Outgoing connections: 8
Incoming connections: 4
Supporting other nodes: Yes

Other
Pi Node version number: 0.4.3
Operating system: WINDOWS 10.0.19042 (Microsoft Windows 10 Pro)
Using Docker Toolbox: No
Node installation date: 2021-04-01
Availability (up to 90 days): 42.16% from 2021-04-01 to 2021-04-19

I didn't do anything other than wait, so it seems that my setup was all OK from the start!!

**Comment by nathusius** [comment]
And here is my log from the Pi Consensus container running on Docker, just in case it is useful for anyone else to compare (this all appears to be running correctly!):

Starting Stellar Quickstart

mode: persistent
network: testnet (Pi Testnet)
postgres user: stellar
using POSTGRES_PASSWORD
finalize-pgpass: ok
init-postgres: ok
Waiting for postgres to be available...
postgres: up
create-horizon-db: ok
create-core-db: ok
stellar-postgres-user: ok
chown-core: ok
finalize-core-config-pgpass: ok
finalize-core-config-run-standalone: ok
finalize-core-config-manual-close: ok
set-private-key: ok
init-core-db: ok
chown-horizon: ok
init-horizon-db: ok
postgres: down
starting supervisor
2021-04-19 11:39:27,240 CRIT Supervisor running as root (no user in config file)
2021-04-19 11:39:27,329 INFO RPC interface 'supervisor' initialized
2021-04-19 11:39:27,330 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-04-19 11:39:27,330 INFO supervisord started with pid 1
2021-04-19 11:39:28,341 INFO spawned: 'postgresql' with pid 370
2021-04-19 11:39:28,368 INFO spawned: 'stellar-core' with pid 371
2021-04-19 11:39:28,391 INFO spawned: 'horizon' with pid 372
2021-04-19 11:39:28,392 INFO reaped unknown pid 359
2021-04-19 11:39:29,762 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-19 11:39:29,762 INFO success: stellar-core entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-19 11:39:29,763 INFO success: horizon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-19 11:43:58,863 INFO waiting for stellar-core to stop
2021-04-19 11:44:00,866 INFO waiting for stellar-core to stop
2021-04-19 11:44:02,191 INFO stopped: stellar-core (exit status 0)
2021-04-19 11:44:02,246 INFO spawned: 'stellar-core' with pid 1136
2021-04-19 11:44:04,116 INFO success: stellar-core entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by marzapps** [comment]
Took a look this morning and saw this message: "Your computer is syncing with the blockchain (it may take hours)"
Yeah! So going to close this issue out as it seems like the fix was to upgrade to Big Sur and just wait.

**Comment by daivu2001** [comment]
![image](https://user-images.githubusercontent.com/103204022/162242825-7e99febc-e00a-40e2-80a6-7d7bfcb63c83.png)
