### ISSUE TITLE
user-preferences.json Shouldn't I use this file?

### ISSUE THREAD

**Issue by mhj0916** [pi-node/instructions#126]
https://github.com/pi-node/instructions/issues/30
Seeing this, I followed up and succeeded.
However, someone tells me not to use this method as it may negatively affect the mainnet node selection or be recognized as a clone.
Is this true?
The reason I used this method is that blocks were not created after being selected as a node, so I formatted my computer and reinstalled the Pi node. Then, from the beginning, I had to wait for the node selection again.
So I used the user-preferences.json file and was able to select it right away and create a block.

**Comment by remzicirit** [comment]
it works, I tested also

**Comment by mhj0916** [comment]
What tests did you do? Isn't it true that it can be recognized as a clone?

**Comment by remzicirit** [comment]
I completely removed old one

**Comment by mhj0916** [comment]
I also know that using this file works fine and creates blocks.
The reason I posted the question was to know if I could be recognized as a clone on the Core Team server if I proceed this way.
And because of that, I wonder if the mainnet node selection could have a negative effect on it. Do you know anything about this?

**Comment by lehboi** [comment]
I have just posted the question in the chat room Node Applicants and one of the moderators has answered:
That is a process of cloning. Be careful, if you do so, your node will be flagged as a cloner in the system. Always do clean installation.

**Comment by remzicirit** [comment]
Thank you Lehboi, I removed  PI node from old server and installed to new server which has recommended  OS as Windows 10, Everything started from 0 again

**Comment by mhj0916** [comment]
lehboi Well looked at your answer. I was frustrated because no one gave a clear answer, but now I know. Thank you so much!
