### ISSUE TITLE
Waiting for postgres to be available.

### ISSUE THREAD

**Issue by remzicirit** [pi-node/instructions#128]
I see in the logs it is repeating this message
![image](https://user-images.githubusercontent.com/83867549/118833118-713ac880-b87e-11eb-97e5-d104dc076862.png)
 and Node troubleshooting page show this
![image](https://user-images.githubusercontent.com/83867549/118833272-8e6f9700-b87e-11eb-8272-b4c060ee7681.png)

![image](https://user-images.githubusercontent.com/83867549/118833389-a21afd80-b87e-11eb-888b-5b1a919d05bb.png)
 Nothing is written postgres logs

![image](https://user-images.githubusercontent.com/83867549/118833674-e0182180-b87e-11eb-8345-a60aa04c63c9.png)

I am not sure if it is running

**Comment by ihatejam** [comment]
Install it on Windows 10  (latest build). I don't know anyone who got past the point you're at on Windows Server. There are historical issues with running a Linux container under Docker on Windows Server.
You really don't need a server class setup for this.

**Comment by remzicirit** [comment]
I finally gave up on  windows 2019 server and switched to  Windows 10 pro. I made it work in windows 2019 server  by installing docker  first , like you said it is unstable.

**Comment by remzicirit** [comment]
jus quick question  after reinstall with windows  10 Pro, all previous settings are gone.  Previous availability rest to zero and  restoring user.conf 
![image](https://user-images.githubusercontent.com/83867549/118901615-f64ecd80-b8d0-11eb-8cab-5aa62e5dbbfc.png)
should I just wait for consensus  container to to be downloaded and run
Thanks

**Comment by ihatejam** [comment]
I'd go through the port checker process again, step-by-step just to be sure - Cos, if you're already a node candidate, when you click to move on after the port-check, it should request a download of the consensus container at that point as far as I can remember. Also would not hurt to check with ipfingerprints to see if your port-forwarding is fine.

If you've already done that, then try leaving it as-is for a few days (in case you're back to having to show your availability as a possible node), in which case the consensus container will be dropped onto your setup later on.

**Comment by remzicirit** [comment]
Thank you interesting Jfingerprints shows port is open

![image](https://user-images.githubusercontent.com/83867549/119192183-f075fb00-ba3c-11eb-9548-919449a2d567.png)
 and container shows they are open
![image](https://user-images.githubusercontent.com/83867549/119192266-13081400-ba3d-11eb-8327-af88c345b555.png)

but port check randomly fails, it speins and spins forever and sometimes comes back says  1 or 2 ports not open as you can see , ifingerprinets and  netstat container status all says it is open

![image](https://user-images.githubusercontent.com/83867549/119192391-52cefb80-ba3d-11eb-9801-ffa46fba9bea.png)

**Comment by nathusius** [comment]
I could never get any results at all from the ports checker, just two ticks and a continuously spinning arrow for pinging, but I am now running the node just fine! If ipfingerprints says all ports are open then you are all good, just leave it running (24/7 if possible) and hope to get picked up soon. Node diagnostics are very suspect and can seem to imply that you have a problem which isn't actually there, so do yourself a BIG favour and just ignore that, as I wasted literally days trying to figure out a non-exisitent issue, doh!! ;-)
