### ISSUE TITLE
Could not get root HAS: Get \"http://testnet-history.minepi.com:31403/.well-known/stellar-history.

### ISSUE THREAD

**Issue by remzicirit** [pi-node/instructions#131]
Hi Team
Node is trying to sync
![image](https://user-images.githubusercontent.com/83867549/119576095-57651e00-bd75-11eb-8a74-de96622ae240.png)

for hours all I am seeing this error 
/var/log/supervisor/horizon-stdout---supervisor-f_KPv8.log
shows this 
time="2021-05-25T22:09:27.358Z" level=error msg="Error in ingestion state machine" current_state=start error="Error gett
ing last checkpoint: could not get root HAS: Get \"http://testnet-history.minepi.com:31403/.well-known/stellar-history.j
son\": dial tcp 161.35.227.222:31403: connect: connection refused" next_state=start pid=399 service=ingest
do I need to worry or issue is related  to http://testnet-history.minepi.com
Thanks

**Comment by remzicirit** [comment]
24 hours later still seems issue with

http://testnet-history.minepi.com:31403/.well-known/stellar-history.json\": dial tcp 161.35.227.222:31403: connect: connection refused" next_state=start pid=39
do we have problem with  http://testnet-history.minepi.com:31403/.well-known/stellar-history.json\

time="2021-05-26T13:12:36.645Z" level=error msg="Error in ingestion state machine" current_state=start error="Error getting last checkpoint: could not get root HAS: Get \"http://testnet-history.minepi.com:31403/.well-known/stellar-history.json\": dial tcp 161.35.227.222:31403: connect: connection refused" next_state=start pid=399 service=ingest
time="2021-05-26T13:12:37.645Z" level=info msg="Ingestion system state machine transition" current_state=start next_state=start pid=399 service=ingest
^C
#

**Comment by remzicirit** [comment]
Testnet seems  it is okay

**Comment by Yoshiaki-Hatada** [comment]
# 131 is finished.  We apologize for the inconvenience.

2021年6月12日(土) 22:05 remzicirit ***@***.***>:
