### ISSUE TITLE
Is there a problem with the location of the log?

### ISSUE THREAD

**Issue by na3ee** [pi-node/instructions#144]
![image](https://user-images.githubusercontent.com/86134876/123386518-b797eb80-d5d1-11eb-9ee4-27bdc778a921.png)

![image](https://user-images.githubusercontent.com/86134876/123386630-d4ccba00-d5d1-11eb-85ce-e1001519e92e.png)

**Comment by ihatejam** [comment]
Everything looks good!

**Comment by na3ee** [comment]
> 모든 것이 좋아 보인다!

God bless you!

**Comment by na3ee** [comment]
God bless you!

**Comment by na3ee** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you and thank you.I hope you have a gift-like day today...
--------- 원본 메일 ---------

    
        보낸사람: ihatejam ***@***.***>
        받는사람: pi-node/instructions ***@***.***>
        
            참조: na3ee ***@***.***>, Author ***@***.***>
        
        날짜: 21.06.25 16:31 GMT +0900
        제목: Re: [pi-node/instructions] Is there a problem with the location of the log? (#144)
        
        
    
    
        
Everything looks good!
