### ISSUE TITLE
31402 Port Continuous Attack

### ISSUE THREAD

**Issue by na3ee** [pi-node/instructions#161]
Since Malwarebytes installation, Troy often blocks websites. Malwarebytes is so busy blocking/removing it. Should I cover Malwarebytes' mouth for complaining?
The attack type is created by outbound.

And what does this mean?

![image](https://user-images.githubusercontent.com/86134876/126969141-e9a3e05b-3234-4d45-a895-25b1a334a6d0.png)

**Comment by ihatejam** [comment]
I run Malwarebytes and I get them from time-to-time too. I haven't had time to look into it, but my node seems to perform well despite whatever Malwarebytes is blocking.

**Comment by na3ee** [comment]
> 나는 Malwarebytes를 실행하고 때때로 그것들을 얻습니다. 살펴볼 시간이 없었지만 Malwarebytes가 차단하고 있음에도 불구하고 내 노드는 잘 작동하는 것 같습니다.


![image](https://user-images.githubusercontent.com/86134876/126984069-aa25c748-6d52-4126-b68c-3aa0e504b933.png)


Malwarebytes is blocking, but it must be working well.
Then you don't have to worry about Malwarebytes complaining.

What does the unknown pid acquisition of the log mean?
