### ISSUE TITLE
consensus container will not reload

### ISSUE THREAD

**Issue by vkozacek** [pi-node/instructions#165]
I have been running PI Node on a Mac for the last few months and the power was pulled by accident. Docker would not reload and has been reinstalled. Port checker container has been reinstalled in docker but does not appear to run and the consensus container won't reload.  I have an alternating status Consensus container: absent and Consensus container: creating but nothing has changed in over 12 hours. 

Is there a way to manually reload the consensus container so that syncing can be restarted? 
![Image 03-08-2021 at 08 32](https://user-images.githubusercontent.com/7250526/127976090-3b7fcdc0-a888-45b8-b4dc-da60f443825f.jpg)

**Comment by ihatejam** [comment]
Hi - I would recommend turning off the "API service" switch on the Troubleshooting screen (unless you are doing some dev work on a Pi app/utility and require access to the API service). After that, I would click the "Remove all blockchain data" to get rid of the chunk of space the API would have used on your hard drive -- Restart everything and then let it run in that state for a while to see if the consensus container is picked back up.

I'm assuming that the port forwarding is still in order - and that if you check using https://www.ipfingerprints.com/portscan.php that ports 31400-31409 are open

(Please don't post screenshots of ipfingerprints without masking your public IP address)

**Comment by vkozacek** [comment]
Hi, thank you for the response, I will try that. 
Yes, the ports are all open still.

<img width="318" alt="Untitled" src="https://user-images.githubusercontent.com/7250526/128013005-6a6b3f44-2f93-41f6-84a3-6db36300bdfb.png">

**Comment by vkozacek** [comment]
Approaching 24hrs with no change, unfortunately.

**Comment by vkozacek** [comment]
Still nothing 36+ hours on. Do you have any other ideas, please? Thanks again for the help.

**Comment by vkozacek** [comment]
The consensus container has finally been installed, I am now waiting for it to catch up. Thank you for the help
