### ISSUE TITLE
why there are 3 failed connections for port 31402 on https://dashboard.pi-blockchain.net/

### ISSUE THREAD

**Issue by jackpinode** [pi-node/instructions#169]
My node had been running well for 5 months until July 30. 
On July 30, the Node can't be open normally, even after clicking Reload, it can't be back displayed normally. 
Then on July 31, the computer was reset via clicking recovery, but the node still can't display normally. 
On August 1, the computer was reset to a new device, then since August 2, the node is stuck on consensus container enabled: No 
On August 8 (yesterday), the number of failed connections to port 31402 is 1, today is 3 on https://dashboard.pi-blockchain.net/.
I checked the ports, all ports are open (I know how to setup the ports because I have run Node for 5 months since Feb 27).
Can anyone give the advice for why there are failed connections to port 31402 on https://dashboard.pi-blockchain.net/.
Thanks!

**Comment by jackpinode** [comment]
![Node running](https://user-images.githubusercontent.com/88670245/128726053-8c0a4b87-f10f-4070-b269-69c388862e57.jpg)
Before July 30

**Comment by jackpinode** [comment]
![Problem 1](https://user-images.githubusercontent.com/88670245/128726165-75634af9-23ef-4b19-9e62-6ebd4f7b21bb.jpg)
Problem on July 30

**Comment by jackpinode** [comment]
![Problem 2](https://user-images.githubusercontent.com/88670245/128726247-98e521c7-02c3-43bd-8abe-35b81efdff5d.jpg)
After computer reset on July 31

**Comment by jackpinode** [comment]
![Node troubleshooting](https://user-images.githubusercontent.com/88670245/128726407-81a24290-f240-48c6-a92f-eab7a5b11008.jpg)
After computer reset to a new device on August 1 and on August 2 showed the troubleshooting results

**Comment by jackpinode** [comment]
![Number of failed connection to port 31402](https://user-images.githubusercontent.com/88670245/128726593-52fe05b8-e01a-4427-b2ee-5ecca2868d4e.jpg)
Failed connections to port 31402 today (August 9)

**Comment by jackpinode** [comment]
![Port scan](https://user-images.githubusercontent.com/88670245/128727404-df5c5c07-c880-4537-a652-ea03148e4757.jpg)
All ports from 31400 through 31409 are open from https://www.ipfingerprints.com

**Comment by ihatejam** [comment]
Since you started over, this node installation is new to the network - Please leave it running as it is now, and wait for it to be recognized as a node candidate - just like you did with your original node device. Once it is recognized as a viable node candidate, the consensus container will be sent down to your device. This could take a while to happen.
