### ISSUE TITLE
am i doing a correct way for node setup?

### ISSUE THREAD

**Issue by gnimeehc** [pi-node/instructions#186]
![image](https://user-images.githubusercontent.com/92090341/136368224-610022b0-172c-4ead-a80e-d2eb8d12a5f7.png)

**Comment by SeedKunY** [comment]
Looks like it doesnot work fine, because consensus container is not enabled. are you using physical machine or virtual machine?

**Comment by gnimeehc** [comment]
> Looks like it doesnot work fine, because consensus container is not enabled. are you using physical machine or virtual machine?

i think is physical machine

**Comment by justin6652** [comment]
consensus container enabled by core team !just keep running ,or direct install version 0.47 auto have consensus container

**Comment by justin6652** [comment]
win10：

dr5alvt1qft56.cloudfront.net/0.4.7/Pi+Network+Setup+0.4.7.exe

Mac：

dr5alvt1qft56.cloudfront.net/0.4.7/Pi+Network-0.4.7.dmg

**Comment by gnimeehc** [comment]
> consensus container enabled by core team !just keep running ,or direct install version 0.47 auto have consensus container

alright thx for explaining
