### ISSUE TITLE
PI Node constantly provide wrong opened port status

### ISSUE THREAD

**Issue by AndyKr0p** [pi-node/instructions#216]
I configured port forwarding on my router and when I test configuration Pi Network randomely shows some ports closed every time when I run "Check now". I checked via online port scannera few times and it shows that all required ports are opened. Macbook on M1, static WAN IP.
Quck check of the logs on the router does not show incoming packets to DPT which are displayed as "NOT OPEN".

<img width="773" alt="Screenshot 2021-12-27 at 10 37 56" src="https://user-images.githubusercontent.com/9101937/147458629-5f393b5d-6731-4ff7-8553-10f0912d6c66.png">
.

**Comment by ihatejam** [comment]
yep - the built-in port checker is not great -- if online port scanners are showing them as open, then you're good. 
Just leave it running with the listener (stellar-dummy) container running for now until the consensus container is sent down to you. This could take a while -- I'm assuming of course that it would make sense for the Core Team to still continue on with the Testnet node deployment while the mainnet runs in the enclosed network stage (enclosed network per the roadmap on the front page announcement currently on the app.)

**Comment by MichaelSaucier** [comment]
Same problem here. How can Mainnet be even close to ready if infrastructure apps are unreliable? The missing prioritizationon on reliability before scale seems wrongly placed. Does the runtime % available continue to accrue correctly when we have verified the ports are open, but the app randomly (and incorrectly) shows some closed?

**Comment by ihatejam** [comment]
@MichaelSaucier The Node software you and I are running is Beta (as per https://node.minepi.com). The built-in checker is known to not be very reliable and so using an external checker is often best (like [ipfingerprints](https://www.ipfingerprints.com/portscan.php)). 

During the current (Enclosed Network) stage of mainnet, only Core Team nodes will be connected to the mainnet blockchain for reasons explained in the [Roadmap](https://bit.ly/PiRoadMap).

Community nodes (which is what you and I are running) will continue to be connected to the testnet and can only be connected to the mainnet once the switch is made to the Open Network stage of the Mainnet - that is when decentralization will start -- The Roadmap published on the front page announcement a while back has more  : [Roadmap](https://bit.ly/PiRoadMap)
