### ISSUE TITLE
Why my node does't show the "Availability"?

### ISSUE THREAD

**Issue by a3761992** [pi-node/instructions#217]
I had install it for 2 weeks,always online.But it  always "N/A"

**Comment by ihatejam** [comment]
New nodes and some older nodes that have been restarted recently will show "N/A" -- for now this is "normal".

**Comment by a3761992** [comment]
> New nodes and some older nodes that have been restarted recently will show "N/A" -- for now this is "normal".

Thank you very much for anwser!~
