### ISSUE TITLE
ich werde alles einmal versuchen

### ISSUE THREAD

**Issue by ghost** [pi-node/instructions#227]
ich werde alles einmal versuchen

**Comment by a3761992** [comment]
Me too.My node always keep in 1-2.But some times it can be 7-9 when  I change my IP.------from GZ China.

**Comment by solocop** [comment]
It depen on your node seed. You can gen to new seed to get more incom

On docker -> Click to icon (>-) CLI. From open terminal enter command **stellar-core gen-seed** -> enter.

Try until you get new node ID (Public) have format GDx with x is a number from 1-9 like below

`    Secret seed: SC7APYI4UDYYTRH64DRM4KAIASV4JREHK3WZIQKGVN6JKO22CMGI67IM
    Public: GD4 UJCCUI7WPTVLSPNFLKNW5VAE23TXFIYA3DFJ2XHEHPZICWRII3VSV`

Copy toàn bộ dãy ký tự của dòng ‘secret seed’ replace NODE_SEED field in file C:\Users\Admin\AppData\Roaming\Pi Network\docker_volumes\stellar\core\etc\stellar-core
ex: NODE_SEED="SC7APYI4UDYYTRH64DRM4KAIASV4JREHK3WZIQKGVN6JKO22CMGI67IM" 

Save file and restart the docker, PI app -> incom will increase to 64 soon
