### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by na3ee** [pi-node/instructions#238]
![2022-02-13](https://user-images.githubusercontent.com/86134876/153750765-b25e8d2c-f6c2-4bae-a1af-1cd897e7792a.png)

**Comment by na3ee** [comment]
There was a phenomenon in which the log was broken after operating the node for nearly a year, but the node was doing well. However, it interfered with my brain, so I deleted the docker and installed it, and this phenomenon occurs. After deleting the docker, there have been several installations, but what is the current problem?

Please understand that English is not my first language.

**Comment by parknochang** [comment]
Uninstall the currently installed Docker and install a lower version of Docker. Docker 3.x.x version is recommended.
Please understand that English is not my first language. <--  me too ^^
download url : https://docs.docker.com/desktop/windows/release-notes/3.x/

**Comment by na3ee** [comment]
> 현재 설치된 Docker를 제거하고 더 낮은 버전의 Docker를 설치합니다. Docker 3.xx 버전을 권장합니다. 영어가 제 모국어가 아님을 이해해 주십시오. <-- 나도 ^^ 다운로드 url : https://docs.docker.com/desktop/windows/release-notes/3.x/



당신의 친절한 답변에 끝없는 감사를 드립니다. 선물 같은 하루 되시길... ^^

Thank you endlessly for your kind reply. I hope you have a gift-like day. ^^
