### ISSUE TITLE
NO INCOMING CONNECTIONS?

### ISSUE THREAD

**Issue by Emekapaul** [pi-node/instructions#261]
I think I have a problem with my Node
Pinging shows all ports OPEN.
Although The external port check program, however, shows me only three ports open 31401-31403.
Is this okay?
I have not really had an incoming connection since I started Node.

Protocol version: Latest
Latest block: a few seconds ago
Outgoing connections: 8
???? Incoming connections: 0 ???? I'm not sure it works right here !?
???? Supporting other nodes: No ???? I'm not sure it works right here !?

Container
Consensus container enabled: Yes
Node switch on: Yes
PortsChecker container: exited
Consensus container: running

I will really appreciate it if someone can explain what's happening. I want to know if this is normal or not. Best regards.

**Comment by arick89** [comment]
Same to me

**Comment by hymcomputer** [comment]
我的也是这种情况。不知道什么原因。请老师们帮忙。
