### ISSUE TITLE
Node reward low 

### ISSUE THREAD

**Issue by AbdellahL** [pi-node/instructions#281]
My node reward went from 5.6 to 2.24 without any explanation. I was wondering if someone can tell me why my node reward decreased. Also, my node was up and running full time without stopping.
<img width="327" alt="Capture d’écran 2022-06-22 à 17 34 18" src="https://user-images.githubusercontent.com/44164251/175072323-bba5da2f-31ef-464f-9ed9-253d0234c32a.png">

**Comment by Yahya814** [comment]
Due to decrease mining by referral team  ,  also base rate is decreasing by time
