### ISSUE TITLE
We couldn't reach the required ports on your machine. Please double-check your configuration.

### ISSUE THREAD

**Issue by julesledev** [pi-node/instructions#297]
The ports are not opened although the configuration

I think that a screenshot will be many meaningful 

![image](https://user-images.githubusercontent.com/71714827/195339533-a1062c32-afc5-41ec-b19b-59a5e4eec0a3.png)
![image](https://user-images.githubusercontent.com/71714827/195339603-48a856ec-c93b-454d-aa23-695ca8d72a6b.png)
![image](https://user-images.githubusercontent.com/71714827/195339764-964b93e8-ed38-4297-a787-0836f5019eea.png)

**Comment by NeyMR** [comment]
join us if your looking for help https://t.me/PiNodechat 

🤓👍

**Comment by julesledev** [comment]
I have 
![image](https://user-images.githubusercontent.com/71714827/195359638-6e507a09-19f6-4d86-91e5-a692dbbf90df.png)

**Comment by dhawanreddy29** [comment]
Even i'm facing same issue, please help me
