### ISSUE TITLE
Certificate Errors in logs related to Node setup - Node setup hangs on loading

### ISSUE THREAD

**Issue by TheZLabs** [pi-node/instructions#301]
All ports are verified open to the outside for inbound connections via YouGetSignal, port check fails.
Node does not connect. Says it may take up to one minute. Container does not download. Certificate errors all through the log.
![image](https://user-images.githubusercontent.com/59536236/210656012-d96ea94e-916f-4298-bfc4-e12fdf3249ea.png)
![image](https://user-images.githubusercontent.com/59536236/210656202-187cf5d5-0725-4502-8ad3-17a1acbd3e5d.png)

Looks like there are other issues with the setup too:
![image](https://user-images.githubusercontent.com/59536236/210656358-0a9532c3-b1f2-4b92-9c65-4d9cdde15a9d.png)

**Comment by NeyMR** [comment]
solution found here https://t.me/PiNodechat

**Comment by TheZLabs** [comment]
Uninstall docker, reboot, reinstall

Manually download latest docker image in Admin cmd prompt or admin powershell:

docker pull pinetwork/pi-node-docker:latest

Make sure Pi Node app is closed, then go to C:\Users\your_username\AppData\Roaming\Pi Network

Edit user-preferences.json
replace everything from here to the end with this:

,"switchStatus":false,
"portsCheckPassed":false,
"dockerImage":"pinetwork/pi-node-docker:latest",
"containerFlavor":"stellar",
"stellarSecretSeed":"",
"stellarConfigVersion":"0.0.9",
"horizonStatusPreference":true,
"testnetResetCount":"2",
"testnetResetLatestNodeUIVersion":"0.4.4"}

Save.

Reboot.

Manually start docker image. Start Pi node 

Works now.

**Comment by chipmoon27** [comment]
Follow this And now you have officially flagged your account

**Comment by TheZLabs** [comment]
why?

**Comment by chipmoon27** [comment]
should not be messing with config files this was reiterated by CT

**Comment by TheZLabs** [comment]
So because I changed my config file to make it work, my account would be flagged? Not sure I understand that. Maybe CT should respond to one of the many many related Open tickets? They won’t do that but they’ll flag my account? 🤔On Wed, Jan 4, 2023 at 6:24 PM chipmoon27 ***@***.***> wrote:
should not be messing with config files this was reiterated by CT

**Comment by cheme75** [comment]
> So because I changed my config file to make it work, my account would be flagged? Not sure I understand that. Maybe CT should respond to one of the many many related Open tickets? They won’t do that but they’ll flag my account? 🤔On Wed, Jan 4, 2023 at 6:24 PM chipmoon27 ***@***.***> wrote: should not be messing with config files this was reiterated by CT —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Fwiw, I totally agree. The CT is out of touch with the reality of the node glitches. My HD crashed but I managed to rescue most all the files from the pi folders. I updated win10 on an old gen 2 i5 laptop, installed pi with a fresh login but copied all my existing files over to new hd, loaded up docker and got nothing but a spinning circle “waiting a minute” to load but never did. After leaving it over night I shutdown, found same info as what you posted about the json file on another site, made the edits, rebooted and bingo, node is back up and actually running much better now. It’s up to date with the blocks where as before the hd crash, it was usually always catching up.

**Comment by TheZLabs** [comment]
> > So because I changed my config file to make it work, my account would be flagged? Not sure I understand that. Maybe CT should respond to one of the many many related Open tickets? They won’t do that but they’ll flag my account? 🤔On Wed, Jan 4, 2023 at 6:24 PM chipmoon27 _**@**_._**> wrote: should not be messing with config files this was reiterated by CT —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> 
> Fwiw, I totally agree. The CT is out of touch with the reality of the node glitches. My HD crashed but I managed to rescue most all the files from the pi folders. I updated win10 on an old gen 2 i5 laptop, installed pi with a fresh login but copied all my existing files over to new hd, loaded up docker and got nothing but a spinning circle “waiting a minute” to load but never did. After leaving it over night I shutdown, found same info as what you posted about the json file on another site, made the edits, rebooted and bingo, node is back up and actually running much better now. It’s up to date with the blocks where as before the hd crash, it was usually always catching up.

So you followed the same steps in changing the user-preferences.json file and also had it work? I'm honestly not sure why this isn't a documented fix being relayed by CT to node users having issues. I get that it's a test net but we all want to see how it works too lol.

**Comment by NeyMR** [comment]
> > > So because I changed my config file to make it work, my account would be flagged? Not sure I understand that. Maybe CT should respond to one of the many many related Open tickets? They won’t do that but they’ll flag my account? 🤔On Wed, Jan 4, 2023 at 6:24 PM chipmoon27 _**@**_._**> wrote: should not be messing with config files this was reiterated by CT —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> 
> > 
> 
> > Fwiw, I totally agree. The CT is out of touch with the reality of the node glitches. My HD crashed but I managed to rescue most all the files from the pi folders. I updated win10 on an old gen 2 i5 laptop, installed pi with a fresh login but copied all my existing files over to new hd, loaded up docker and got nothing but a spinning circle “waiting a minute” to load but never did. After leaving it over night I shutdown, found same info as what you posted about the json file on another site, made the edits, rebooted and bingo, node is back up and actually running much better now. It’s up to date with the blocks where as before the hd crash, it was usually always catching up.
> 
> 
> 
> So you followed the same steps in changing the user-preferences.json file and also had it work? I'm honestly not sure why this isn't a documented fix being relayed by CT to node users having issues. I get that it's a test net but we all want to see how it works too lol.

this can be wrongly used and is not accepted to post on here, you should remove post as it will do more harm than good.

**Comment by NeyMR** [comment]
what happens when you break the operators json how will you fix it?

**Comment by cheme75** [comment]
Ya, same “corrections” in the json. Had to dig through some searches and found it in a foreign language post somewhere. First time failed but then found followup post with the “horizon” part and it seemed that did the trick.
