### ISSUE TITLE
Vulnerabilities in pi network pi node docker

### ISSUE THREAD

**Issue by cippo71** [pi-node/instructions#313]
Hi everybody. Pi network has a lot of vulnerabilities. Is there someone who can help?
![Immagine000](https://user-images.githubusercontent.com/129554262/229228057-9a78d4cf-e259-46d8-9a51-334bfa49556e.png)

**Comment by silver-surfer-wolf** [comment]
I can perform a "free of charge" security penetration test.

**Comment by cippo71** [comment]
Hi silver surfer! Thank you very much. Someone by Pi network told me these vulnerabilites aren't a problem.
What do you need to do a "penetration test"? Is it safe?
Best regards

**Comment by silver-surfer-wolf** [comment]
It is safe; I'm not going to do any harm to the system. I just need the IP or domain for the target needed to be tested.
