### ISSUE TITLE
stuck Joining SCP

### ISSUE THREAD

**Issue by disheng34148** [pi-node/instructions#331]
stuck Joining SCP
Restarting the docker and desktop cannot solve the problem
err: Error: disk name invalid and / not found
<img width="436" alt="image" src="https://github.com/pi-node/instructions/assets/28046019/2c226350-514d-4b27-a8f6-9f25ead326a6">

**Comment by cimu34148** [comment]
<img width="772" alt="屏幕截图 2023-10-18 162143" src="https://github.com/pi-node/instructions/assets/28046019/ccb5a7a2-92bc-45cc-8ac7-5dab9d5c9398">

**Comment by nhatvhm** [comment]
@disheng34148  This seems like your Windows 11 was not supporting for Pi Node. Please make sure the window version is Windows 11 Pro. Also, the docker version (Docker Desktop Installer 4.20.1) is working fine with Pi Network Setup 0.4.5 to check Ports 31400-31409

![Screenshot 2023-10-23 130339](https://github.com/pi-node/instructions/assets/7055239/3e0c4bc7-1a76-4073-808b-0f05809fabc3)

**Comment by disheng34148** [comment]
![image](https://github.com/pi-node/instructions/assets/28046019/817e68cc-47bb-4a1b-84a5-b8f2688af50c)
![image](https://github.com/pi-node/instructions/assets/28046019/9b98db3f-dfdd-4870-9ef9-4d203605e576)
![image](https://github.com/pi-node/instructions/assets/28046019/e0b291d2-de46-435b-817f-405b484cdbd7)


My computer is Windows 10 Professional Edition，Docker Desktop is 4.20.1，https://pi-mods.de/nodeports/ ports open。I just don’t know why it keeps getting stuck Joining SCP

**Comment by nhatvhm** [comment]
@disheng34148 No. Don't trust that site. Please make sure you have done this before you turn the Node on (the screenshot's checking all ports should be opening on Pi Node)
![Screenshot 2023-10-28 162015](https://github.com/pi-node/instructions/assets/7055239/d0c5433e-6f45-4075-bb61-1685e2fa279d)
BTW. After you have completed step above. You only see 3 ports are opening 31401, 31402 and 31403, the remaining ports should be closed on https://pi-mods.de/nodeports/

**Comment by disheng34148** [comment]
@nhatvhm Thank you, I have determined that the problem is due to VPN

**Comment by fanxiaofan9** [comment]
问题怎么解决的
