### ISSUE TITLE
Pi Node 4.11 remains on the Turn the Node on for testing page.

### ISSUE THREAD

**Issue by openet001** [pi-node/instructions#359]
env:
Docker 4.26/4.29+PI Node 4.11+Windows 10 22H2 19045.4291 is the same.

Is it normal for Pi Node 4.11 to remain on the Turn the Node on for testing page? 
Only container Stellar-dummy( node-port-test）can be start, 
pi node Docker : last cannot be clicked to start, 

and this situation has been ongoing for several days.

**Comment by Hxnavy** [comment]
same issue

**Comment by openet001** [comment]
delete two files in  C:\Users\\{**your user name folder**}\AppData\Roaming\Pi Network\ , 
1. user-preferences 
2.user-preferences.json ,  
keep running docker 
reinstall pinetwork0.4.11.exe , synced blockchain data and  it's OK now.  

be carefull  backup the above 2 files first.

**Comment by openet001** [comment]
resolved by my self and  referenced isue 368   https://github.com/pi-node/instructions/issues/368
