### ISSUE TITLE
Pi Node have an issue with counter availability is negative number percent on the re-installed Pi Node.

### ISSUE THREAD

**Issue by nhatvhm** [pi-node/instructions#376]
My Pi Node still have node bonus, but I have an issue on my Pi Node displaying the counter availability running Pi Node is negative number percent. 

![Pi Node issue](https://github.com/user-attachments/assets/ad4834db-d66b-40ab-92d2-133fe442daf0)

Reproduce this issue: I run normally Pi Node 1 year ago. When my server crashed due to SDD got problem bad sector.
After that, I've changed SSD then install new Windows and also install Pi Node again.

I would like to report this issue to PCT. Please take a look on this.

**Comment by hadriel02** [comment]
Hi, it was repaired in last config update. Availability counting now should work fine (givw it few days to update).

**Comment by nhatvhm** [comment]
@hadriel02 Thank you!

You were right. However, I see availability percent running Pi Node is greater than 100%. Why? Still have issue now.

![AABBC](https://github.com/user-attachments/assets/43e7efc8-ecd0-4b96-89f9-25cfd08c940c)

**Comment by hadriel02** [comment]
Take it easy, counter will repair itself within few days :-)

**Comment by nhatvhm** [comment]
@hadriel02 It's good. Thank you.
![Csdfure](https://github.com/user-attachments/assets/f82c8a34-e1bb-4c30-b248-8e02b6981a4e)

**Comment by ihtishamkhan1234** [comment]
> My Pi Node still have node bonus, but I have an issue on my Pi Node displaying the counter availability running Pi Node is negative number percent.
> 
> ![Pi Node issue](https://github.com/user-attachments/assets/ad4834db-d66b-40ab-92d2-133fe442daf0)
> 
> Reproduce this issue: I run normally Pi Node 1 year ago. When my server crashed due to SDD got problem bad sector. After that, I've changed SSD then install new Windows and also install Pi Node again.
> 
> I would like to report this issue to PCT. Please take a look on this.

[ ] 

> [/](url)
