### ISSUE TITLE
The Computer Is Not Running The Blokcahin

### ISSUE THREAD

**Issue by mrkzk2012** [pi-node/instructions#383]
Even though I did the features mentioned in this title, the problem was not solved 
https://github.com/pi-node/instructions/issues/353
I use vds to run node. I have 180 gb hard disk space. Whenever i get to 19/21 pi-consenuns disappears from the docker app and i get " your computer is not running the blokchain "error from pi node. The ports are open until 19/21, but after that the ports are closed. How can i solve this?

**Comment by yongkang666git** [comment]
这个简单，我经常遇到这样的情况。能处理的。中国大陆地区。
