### ISSUE TITLE
Pi Node on Mac M3

### ISSUE THREAD

**Issue by RumoursGR** [pi-node/instructions#384]
I’ve installed Docker Desktop (v4.34.0) for Mac M3, I’ve opened the appropriate ports in my router, and I’ve checked everything has got the green light. Then the node started loading up in order to run the blockchain. That’s all - after three days it’s still loading. Any solutions?

I apologize in advance for my newbie pace in this.

Many thanks.

**Comment by NET6666STREEM** [comment]
Yeah I'm very new myself I'm going to learn and force myself to get where I
need to be God bless
