### ISSUE TITLE
Pi Node: Manual Installation on a Mac Silicon

### ISSUE THREAD

**Issue by RumoursGR** [pi-node/instructions#385]
I have found by browsing online a different way to install the Pi Node on a Mac Silicon.

Here it is:

1. Install Docker
2. Install the Pi Node app, open it, but don't let it run the node.
3. Close the Pi Node app.
4. From Docker Desktop, look for the pinetwork/pi-node-docker:latest image and pull it.
5. Start the container for the first time, but tell it to store the image on ~/Users/yourMacUsername/Library/Application Support/Pi Network/docker_volumes (needless to say, replace "yourMacUsername" with what you have on your machine).
6. Start the Pi Node.

However, and while the node is running well, I can't be sure whether it is connected to my Pi Mine app.

What follows is the container inspection output. What is there that could be "saying" that my unique identifier(s) is/are not, or wrongly, set? Please comment freely.

Many thanks!

[
    {
        "Id": "4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645",
        "Created": "2024-09-15T01:56:53.065853713Z",
        "Path": "/start",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9525,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-09-15T01:56:53.103633629Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:fc2710fa3f9cc32771c5a27f3d9b3a57a805ad94cfb293f3c2f9ec68cda5f39b",
        "ResolvConfPath": "/var/lib/docker/containers/4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645/hostname",
        "HostsPath": "/var/lib/docker/containers/4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645/hosts",
        "LogPath": "/var/lib/docker/containers/4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645/4ea689ace8d08c910950e0dfd55a0a507eb1047570c28ce81b5a348d63443645-json.log",
        "Name": "/objective_leakey",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "4ea689ace8d0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "31402/tcp": {},
                "5432/tcp": {},
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "POSTGRES_PASSWORD=ZIAmKQO2ZYRTfmlElGfI",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STELLAR_CORE_VERSION=15.2.0-440.54b03f7.xenial",
                "HORIZON_VERSION=1.13.1-94"
            ],
            "Cmd": null,
            "Image": "pinetwork/pi-node-docker:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/start"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9344a50c70c8d1a03bd7907d83f63fcdfb008dbec3a9d6f7474e2277f97dd325",
            "SandboxKey": "/var/run/docker/netns/9344a50c70c8",
            "Ports": {
                "31402/tcp": null,
                "5432/tcp": null,
                "8000/tcp": null
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "14eac0d20efa72f3f12be4e34cd9276a64509ae123df132635b562eaf077c446",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null,
                    "NetworkID": "ad3e552649c507e384e30011d026dfbae4fa2601d72a9576766737abbd1aad0a",
                    "EndpointID": "14eac0d20efa72f3f12be4e34cd9276a64509ae123df132635b562eaf077c446",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": null
                }
            }
        }
    }
]

**Comment by nhatvhm** [comment]
@RumoursGR Don't touch anything on configuration file. You just download app Pi Node and Docker then setup them. Everything is automatically!

**Comment by RumoursGR** [comment]
Thank you, @nhatvhm. Ok, the node is NOT running the blockchain loading, while trying to create the consensus container for forever now. Something is not working properly. Could you kindly help me fix this?

**Comment by nhatvhm** [comment]
@RumoursGR Almost problems which people got issues related to ports were not opened and not mapped IP address in Firewall and Router on their Mac.  Others thing you have to sure your ISP (Internet Service Provider) didn't block any ports 31400-31409 forwarding in Router as well. That cause by Pi Node won't running and the Pi consensus container is loading forever.
