### ISSUE TITLE
Apple M1 Silicon support

### ISSUE THREAD

**Issue by djgalati** [pi-node/instructions#48]
Hello, Im looking to run a node on my Macbook Pro with the new M1 chip and I wanted to check if the new chip will be supported. I saw that docker is not fully updated to support it yet but once they do release the Apple Silicon version, will there be other road blocks the pi team will have to overcome?

**Comment by djgalati** [comment]
I didn't realize they had a preview available so i am able to able to run this. please disregard this issue.

**Comment by X-Mation** [comment]
How did you run it, as I'm having the same issue

**Comment by applemilk84** [comment]
Pi node in Mac M1 cpu always crash every 22 hours.
M1 cpu 16GB
