### ISSUE TITLE
Windows 10 Home Enable HyperV!! No VMbox. Comcast Business Made firewall exceptions, Added port-forwarding on router but some ports not open(changing) pi node

### ISSUE THREAD

**Issue by codytyler** [pi-node/instructions#52]
I was having this issue Where not all my ports would open the real issue was not having HyperV avalible in Windows 10 home
after I installed docker, 
Control panel firewall>advanced settings>outbound Rule>new rule> tcp 31400-31409
Used my IP address and default router login info( google:" default router login", your router model number is in your network display visible from windows control panel)
added port forwarding for the same tcp/udp 31400-31409(first port31400.........last port 31409)

now when i ran tests only SOME ports(random as i did several tests, would be open)

digdigdig

On pi site it says that Windows pro or enterprise is required in order to enable HyperV or else you must use VM box, ,,,,,,, not the case!

My issue then was that I couldn't have all the ports open even with the docker virtual space. 
after doing all the things above i found these bat file that enables HYPERV in windows 10 Home

Bat file and instructions found here... 

https://schophel.wordpress.com/2020/11/13/how-to-enable-hyper-v-on-windows-10-home/#:~:text=Enable%20Hyper-V%20in%20Windows%2010%20Home%201%20Download,Windows%20updates%20screen%20upon%20restart.%20More%20items...

Give it time you will eventually be prompted to restart from command prompt line
it repeated the same download 100% complete several times before prompting me

right click run as admin
now I have Hyper V enabled.
Still not getting all the ports opened, when I test, I will keep this thread updated as to if i find a solution, every few tests it will say all ports open,

**Comment by codytyler** [comment]
![image](https://user-images.githubusercontent.com/48185848/106322666-0449e700-622b-11eb-8493-96958957442e.png)

**Comment by codytyler** [comment]
![image](https://user-images.githubusercontent.com/48185848/106322737-23e10f80-622b-11eb-8434-5c248c7b0901.png)

**Comment by codytyler** [comment]
two tests ran without changes inbetween above describes my issue

**Comment by codytyler** [comment]
after I ran this in the command prompt i am repeatedly getting all open results...

ISSUE RESOLVED command found below
Make sure to run Command line as administrator

NO VM BOX IS RUNNING  besides docker 

docker run -d -p 80:80 docker/getting-started


![image](https://user-images.githubusercontent.com/48185848/106330333-e040d280-6237-11eb-92c0-94fe0bf9f262.png)

**Comment by codytyler** [comment]
![comcastConfig](https://user-images.githubusercontent.com/48185848/106331140-3febad80-6239-11eb-8597-69eb273d0c23.jpg)
![comcastRuleeg](https://user-images.githubusercontent.com/48185848/106331143-40844400-6239-11eb-8404-b9861d4b5903.jpg)
![ipconfigDiagram](https://user-images.githubusercontent.com/48185848/106331144-411cda80-6239-11eb-8990-d1dd79e5ed81.jpg)

**Comment by codytyler** [comment]
still fully operational!!

![image](https://user-images.githubusercontent.com/48185848/106331413-c0121300-6239-11eb-807b-b84fbef599e5.png)

**Comment by ihatejam** [comment]
guess you've already discovered this - but just in case your post leaves anyone guessing. 
Up until a few months ago Docker Desktop could not run on Windows 10 Home. Win10Home users were forced to run the legacy Docker Toolbox which required HyperV.
This is no longer the case!! 
Like those on Windows 10 Pro, anyone who has updated to the latest build of Windows 10 Home (through windows update), can install the latest Docker Desktop which leverages WSL2 to get you going. 
Configuring the node on Docker Desktop is a bit simpler than with Toolbox.
To sanity-check the open port results showed in the app, I find this site useful - https://www.ipfingerprints.com/portscan.php
Also in case you missed it, they've bumped the Node release to version 0.4.1 yesterday .

**Comment by codytyler** [comment]
Thank you for the update i will update my Node version

**Comment by codytyler** [comment]
https://node.minepi.com/node/
