### ISSUE TITLE
Trouble loading and running Consensus container

### ISSUE THREAD

**Issue by lehboi** [pi-node/instructions#67]
Hi everybody,
I installed Pi Node on Windows 10 a few day ago. I successfully installed PortsChecker container and selected as Node candidate.
Troubles happened when I switched on the red button to start running node consensus.
First problems is Pi Node continuously spawned up to a hundred of child processes that ate all of my memory. I switched off the red button and waited for while, then I saw the node consensus image in Docker Desktop.
I switched the red button on again and got the following errors in Docker Desktop log
`Starting Stellar Quickstart

mode: persistent
network: testnet (Pi Testnet)
postgres: config directory exists, skipping copy
supervisor: config directory exists, skipping copy
stellar-core: config directory exists, skipping copy
horizon: config directory exists, skipping copy
postgres: already initialized
chown-core: ok
finalize-core-config-pgpass: ok
finalize-core-config-run-standalone: ok
finalize-core-config-manual-close: ok
set-private-key: ok
Waiting for postgres to be available...
Waiting for postgres to be available...
Waiting for postgres to be available...
Waiting for postgres to be available...
Waiting for postgres to be available...
postgres: up
init-core-db: failed!

2021-02-15T09:44:01.386 [default INFO] Config from etc/stellar-core.cfg
2021-02-15T09:44:01.397 [default INFO] Using QUORUM_SET: {
   "t" : 2,
   "v" : [ "testnet1", "testnet2", "testnet3" ]
}

2021-02-15T09:44:01.400 GDEJ6 [Database INFO] Connecting to: postgresql://dbname=core host=localhost user=stellar password=********
2021-02-15T09:44:01.468 GDEJ6 [default INFO] Application destructing
2021-02-15T09:44:01.469 GDEJ6 [default INFO] Application destroyed
2021-02-15T09:44:01.469 GDEJ6 [default FATAL] Got an exception: Cannot establish connection to the database.
FATAL:  password authentication failed for user "stellar"
FATAL:  password authentication failed for user "stellar"

2021-02-15T09:44:01.469 GDEJ6 [default FATAL] Please report this bug along with this log file if this was not expected
`
Pi Node tried to start Consensus container endlessly but failed.

After that, I deleted the consensus image in Docker Desktop and switched the re button on again, the problem re-appeared.

What are wrong with my computer?
Thank you in advance!
Boi Le

**Comment by Zantiki** [comment]
Try ssh-ing into the consensus-container/pressing the terminal-icon on docker desktop and running the following command in the terminal that should open: 
`sudo service restart postgresql`.

**Comment by lehboi** [comment]
After failing many times, I installed it on another computer and it worked.
