### ISSUE TITLE
Stellar-core service/process does not start within consensus container

### ISSUE THREAD

**Issue by Zantiki** [pi-node/instructions#68]
After ssh-ing into the docker-container and checking what services are active, stellar is not running (and neither is its database).
When attempting to run the stellar-core process as described in the stellar documentation, it outputs the following error:

![image](https://user-images.githubusercontent.com/55238744/108191362-5340b900-7113-11eb-8e75-1202aed068f4.png)

**Comment by Zantiki** [comment]
Temporary fix by ssh-ing into consensus container and restarting postgresql service manually.

**Comment by lavrentius-dev** [comment]
Hi, I suppose the consensus container is something you get after you are selected to run a test node? Trying to understand if my installation is correct as it didn't include one. There is only one item on the list, 'stellar-dummy'.

**Comment by Zantiki** [comment]
Hi! Stellar-dummy is the port-checker container. If you're not getting any errors on the port-checking then you should be fine. Getting selected for running Nodes is dependent on two things: having the most recent node update and up-time over the past 6 months or so. If you're not seeing a docker container called consensus-something, that should mean you have not been selected yet. Best course of action is to just leave your node on for a while, and it'll get selected eventually.
