### ISSUE TITLE
Some ports are not open occasionally when click "Check Now" on mac

### ISSUE THREAD

**Issue by wangcarlton** [pi-node/instructions#77]
Hey,

I've installed Pi node for 3 days, I set up the firewall for "allowing incoming connections", and also configured port fowarding on my router. But I've got two questions:
1. Sometimes, when click "Check Now", few ports are "Not Open", and after several seconds, click again, all ports are open.
2. In the final page "Troubleshooting", it always saying "Consensus container enabled: No" and  "Consensus container: error", I've let my machine ran at least 50% during past 3 days, but it still shows only 7.5% availability.

Thank you.
<img width="549" alt="Screen Shot 2021-02-28 at 11 14 21 pm" src="https://user-images.githubusercontent.com/35724343/109418284-bee02b80-7a1b-11eb-99dc-bdaede852c7d.png">
<img width="510" alt="Screen Shot 2021-02-28 at 11 15 26 pm" src="https://user-images.githubusercontent.com/35724343/109418287-c273b280-7a1b-11eb-985a-bc41593f0033.png">
<img width="564" alt="Screen Shot 2021-02-28 at 11 15 38 pm" src="https://user-images.githubusercontent.com/35724343/109418288-c30c4900-7a1b-11eb-9241-937901c78f15.png">

**Comment by codytyler** [comment]
docker run -d -p 80:80 docker/getting-started

**Comment by codytyler** [comment]
try plugging that into the comand prompt

**Comment by codytyler** [comment]
https://github.com/pi-node/instructions/issues/52

**Comment by ihatejam** [comment]
You're fine - the built-in checker port checker is a bit temperamental. My favorite place to sanity check a port forwarding config is https://www.ipfingerprints.com/portscan.php

**Comment by wangcarlton** [comment]
yeah, but it still says "Consensus container enabled: No" and "Consensus container: error"
And the "Availability (up to 90 days): 7.50% from 2021-02-25 to 2021-02-26" still there, I left my laptop all open the whole weekend :(

**Comment by ihatejam** [comment]
"Consensus container enabled: No" is normal - it will only change once you are selected as a node candidate (based on your node availability). Once that happens, the consensus container is pushed to your PC and it will change to "Consensus container enabled: Yes".

Your availability statistics will become more accurate as you approach a full 90 day window.

**Comment by wangcarlton** [comment]
It's working perfectly now, thank you
